variables:
  LAMBDA_NAME: "default"
  PACKAGE_NAME: "${LAMBDA_NAME}-python-packages"
  AWS_DEFAULT_REGION: "ap-southeast-2"

stages:
  - iac
  - deploy

build-infras:
  stage: iac
  image: python:3.10
  before_script:
    - wget https://releases.hashicorp.com/terraform/1.6.4/terraform_1.6.4_linux_amd64.zip
    - unzip terraform_1.6.4_linux_amd64.zip
    - mv terraform /usr/local/bin/
    - terraform --version
    - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    - unzip awscliv2.zip
    - ./aws/install
    - aws --version
    - export AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID_FPT"
    - export AWS_SECRET_ACCESS_KEY="$AWS_SECRET_ACCESS_KEY_FPT"
  script:
    - cd infras-tf
    - terraform init
    - terraform plan
    - terraform apply -auto-approve
deploy-layer:
  stage: deploy
  image: python:3.10
  before_script:
    - apt-get update
    - apt-get install -y jq
    - apt-get install zip
    - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    - unzip awscliv2.zip
    - ./aws/install
    - aws --version
    - export AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID_FPT"
    - export AWS_SECRET_ACCESS_KEY="$AWS_SECRET_ACCESS_KEY_FPT"
  script:
    - mkdir -p python/lib/python3.10/site-packages/
    - pip install -r requirement.txt --target=python/lib/python3.10/site-packages/
    - zip -qr9 ${PACKAGE_NAME}.zip python
    - layer_arn=$(aws lambda publish-layer-version --layer-name ${PACKAGE_NAME} --zip-file fileb://${PACKAGE_NAME}.zip --compatible-runtimes python3.10 --region ${AWS_DEFAULT_REGION} | jq -r '.LayerVersionArn')
    - aws lambda update-function-configuration --function-name ${LAMBDA_NAME} --layers $layer_arn
  tags:
    - demo

deploy-lambda-code:
  stage: deploy
  image: python:3.10
  before_script:
    - apt-get update
    - apt-get install zip
    - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    - unzip awscliv2.zip
    - ./aws/install
    - aws --version
    - export AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID_FPT"
    - export AWS_SECRET_ACCESS_KEY="$AWS_SECRET_ACCESS_KEY_FPT"
  script:
    - zip -r function.zip dependency.py main.py
    - aws lambda update-function-code --function-name ${LAMBDA_NAME} --zip-file fileb://function.zip
    - aws lambda wait function-updated --function-name ${LAMBDA_NAME}
    - aws lambda update-function-configuration --function-name ${LAMBDA_NAME} --region ${AWS_DEFAULT_REGION}
  tags:
    - demo
